### ISSUE TITLE
[GUI][MAC OS] xION messages too small to read

### ISSUE THREAD

**Issue by mdpfeiffer** [ioncoincore/ion-v4#125]
![screen shot 2019-02-28 at 3 12 56 pm](https://user-images.githubusercontent.com/1129489/53595515-7e6b2000-3b6b-11e9-96a4-2847b6eeec98.jpg)

The xION message font is even smaller than the hover text font. The GUI does not let the user change the text size or zoom in on it, making it hard to read. 

Suggestion: Increase display size of text.Message: Enter an amount > 0.

Software Version:
Ion Core version v3.1.01 (64-bit)
downloaded from https://github.com/ioncoincore/ion/releases
Running on Mac OS 10.14

**Comment by raid12345678** [comment]
@mdpfeiffer  Thank you for your submission one of your Devs will be looking into this issue

**Comment by ckti** [comment]
Have opened pull request #130 for this

**Comment by cevap** [comment]
Text being smaller is better than bigger, especially as there are quite long lines, I would even make it smaller, not bigger, so that more fits.

Beside the point that trying to mint 0 coin produces this message telling you correctly that amount must be bigger than 0 which is more than logical.

Point here is actually not that message, but the one where you really create/mint coins and normally, you will probably copy it to a text editor which shows properly for you.

I would have not merged PR #130

**Comment by cevap** [comment]
test delete comment
