### ISSUE TITLE
[bug] Output index in Qt transaction history is always 0

### ISSUE THREAD

**Issue by AtomSmasher00** [ioncoincore/ion-v4#135]
This is a repost from https://github.com/cevap/ion/issues/32.

**Describe the issue**

All transactions in the history list display an Output index of 0. It doesn't seem to be getting the actual value. This is especially troublesome when setting up a masternode with a 20k output index > 0.

**Can you reliably reproduce the issue?**

Yes, it's every transaction.

**If so, please list the steps to reproduce below:**

Simply make a transaction with a couple outputs (so you for sure get an output index of 1 or higher) from one wallet to another wallet, and compare the transaction history with Chainz or the built-in block explorer. Double click the test entry in the transaction history or right-click to show transaction details.

**Expected behavior**

It should return a 1 or higher when that is the case.

**Actual behavior**

It returns a 0.

**Screenshots**

For privacy reasons, I won't do this, and a redacted screenshot wouldn't prove anything. It's easy enough to see for yourself.

**What version of Ion Core are you using?**

3.1.01 macOS High Sierra.

**Machine specs:**

    2017 Macbook Pro: High Sierra

**Comment by cevap** [comment]
I tried to understand what here the problem is at all. I just guess that you are speaking about your best practices about how to create a masternode and there are really many ways which lead to Rome, so I tried to understand what actually disturbs you and why, please correct me if I am wrong.

## Your MN setup guide, with Ion QT
1. you launch your QT and wait until it is synced
2. you go to your receiving addresses and create one address
3. you send coins to that one address.
4. As you say that if you do use many addresses, it means you try to setup more than 1 masternode by sending 20k to different addresses which you created in previous step.
5. Now you see the TX and then
5.1 you click with right mouse on it and you choose to view TX in transaction details pop up
5.2 **HERE YOU WOULD LIKE TO HAVE THEM ALL LISTED, AS FROM CURRENT SETUP IT SOUNDS EVEN LOGICAL THAT THIS INFORMATION SHOULD BE THERE**. (_this is only my assumption_)
5.3 What you do now, you are forced either to use
5.3.a.1 Blockexplorer and simply pasting txid into search field which would not only let you see them all but also to click through them. On that point you would have then all information. So, now a logical question would be, why do you make steps 5.1 and 5.3 is you can instead of 5.1 and showing TXID window simply copy TXID and paste into your blockexplorer.
5.3.b.1 Here the same goes like in 5.3.a.1, where you could open debug console (**which has autosuggestion**).
5.3.b.2 you type `masternode outputs`, where after pressing just `m` autosuggestion will suggest you as first masternode. Now 5.3.b.1 is not master if you setup single masternode, but you are much faster if you setup multiple and here you would get only outputs for your masternode as well as their ID's.
5.3.c.1 like always cli/debug console would be fastest, where QT's debug window is better suited for beginners, especially because autosuggestion. However, all steps could be done with cli and shell in one command line with usage of sendfrom "addressLabel" "ToIONAddress" amount minconf "comment". Checkout `help sendfrom` and `help sendmany`

This would be some very simple dummy script which everybody can read, now if I setup once a masternode, I probably wouldn't even bother in writing here. Additionally, a masternode can be a lot worth and people who have 1 or 2 masternodes, they really are more scared about using wrong address, value due to the etc... . That is why it would be recommended to for newbies to use 

1. go to receive tab and create payment request of 20000 ION (for the screenshot I will use 10 tION)
2. click on request payment
![grafik](https://user-images.githubusercontent.com/24996551/55200716-bb085680-51bf-11e9-9408-f5f14448f99d.png)
3. write 20000 into amount field and optionally a comment if you require any (some who pay tax find it useful)
![grafik](https://user-images.githubusercontent.com/24996551/55200806-3b2ebc00-51c0-11e9-8ea1-270ca0725728.png)
4. choose/create your address (notice, here you do it in one step, not like in 1-5)
![grafik](https://user-images.githubusercontent.com/24996551/55200738-d6736180-51bf-11e9-994a-9c713cffc222.png)

5. click on as example copy URI or if you use mobile wallet with coins on it, you can scan QR code too
![grafik](https://user-images.githubusercontent.com/24996551/55200871-9496eb00-51c0-11e9-9da1-c739ec881e89.png)

6. Now click on File => Open URI (or press Alt+U) and either paste your uri into the field, however, some might have saved their payment request to a file and you can load it by clickin on a button:
![grafik](https://user-images.githubusercontent.com/24996551/55200943-eb042980-51c0-11e9-98e0-2ab1715c17a5.png)

![grafik](https://user-images.githubusercontent.com/24996551/55201003-38809680-51c1-11e9-91e0-49fb3759b886.png)

_if you forgot to copy or to save, change to receive tab and simply double click on your request to open it_

clicking on ok and this will appear:
![grafik](https://user-images.githubusercontent.com/24996551/55201025-50581a80-51c1-11e9-9027-c67bc22aa3ad.png)

This is fully managable and if you open several uris after each other, all of them will be added as one transaction. This is the only and actually should be official way of setting a masternode with our GUI, but I am for sure not really excited about changes which as addition propagate wrong "Best practices", as going back to the discussion about listing full information instead of a short in Details tab, where would requests then end and will they maybe end with people actually asking for a blockexplorer which has all those nice details.

Beside that you could use different tools as well as some masternode tools provided by different sources, it is always and the best and the fastest way if you do it properly and that start with backing up your masternode private keys before you send anything to that address, arguing that people are not clever enough to use software is never good, as it is the first step ever which every user should do and thats to backup your private key, as for scripts, here, I wrote it in few minutes.

this could be packed into one liner, I splitted it with comments for you:
```bash
# create new address
n1address=$(src/ion-cli --testnet --rpcpassword=123 --rpcuser=123 --rpcport=23451 getnewaddress)
# create new genkey
mngenkey=$(src/ion-cli --testnet --rpcpassword=123 --rpcuser=123 --rpcport=23451 masternode genkey)
# send 10 coins with at least 6 confirmations from sendToMN1Label to previously generated address
txid=$(src/ion-cli --testnet --rpcpassword=2nd --rpcuser=2nd sendfrom "sendToMN1Label" ${mn1address} 10 6 "4Atomsmasher")
# get your external ip
masternodeaddr=$(curl ipinfo.io/ip)
echo "#-----IonCoin.Conf-----" > ioncoin-mn1.conf
echo "server=1" >> ioncoin-mn1.conf
echo "daemon=1" >> ioncoin-mn1.conf
echo "enablezeromint=0" >> ioncoin-mn1.conf
echo "masternode=1" >> ioncoin-mn1.conf
echo "masternode=1" >> ioncoin-mn1.conf
echo "masternodeprivkey=${mngenkey}" >> ioncoin-mn1.conf
echo "externalip=${masternodeaddr}" >> ioncoin-mn1.conf
echo "port=65431" >> ioncoin-mn1.conf
echo "rpcport=65432" >> ioncoin-mn1.conf
echo "masternodeaddr=${masternodeaddr}:12700" >> ioncoin-mn1.conf
echo "#mn1 ${masternodeaddr}:12700 ${mngenkey} 0" > masternode.conf
echo "mn1 ${masternodeaddr}:12700 ${mngenkey} 1" >> masternode.conf

echo "I created new ion address to show Atomsmasher how even one liner could be reused, masternode collateral address: ${mn1address}, genkey: ${mngenkey}, txid: ${txid}, external ip: ${masternodeaddr}. Now imagine that you could use for i in, and setup unlimited amount of mn's (well, limited by coins)";
```

You can simply copy and paste it, this would be the result (if your clients, ports are correct, script is really selfexplainable):
```bash
$ # create new address
$ n1address=$(src/ion-cli --testnet --rpcpassword=123 --rpcuser=123 --rpcport=23451 getnewaddress)
$ # create new genkey
$ mngenkey=$(src/ion-cli --testnet --rpcpassword=123 --rpcuser=123 --rpcport=23451 masternode genkey)
$ # send 10 coins with at least 6 confirmations from sendToMN1Label to previously generated address
$ txid=$(src/ion-cli --testnet --rpcpassword=2nd --rpcuser=2nd sendfrom "sendToMN1Label" ${mn1address} 10 6 "4Atomsmasher")
$ echo ${txid}
647c83dbed690ff63076fb176b1256d038e5c1463fb0c9315b838fe4a54c2dfc
$ # get your external ip
$ masternodeaddr=$(curl ipinfo.io/ip)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     51      0 --:--:-- --:--:-- --:--:--    51
$ echo "#-----IonCoin.Conf-----" > ioncoin-mn1.conf
$ echo "server=1" >> ioncoin-mn1.conf
$ echo "daemon=1" >> ioncoin-mn1.conf
$ echo "enablezeromint=0" >> ioncoin-mn1.conf
$ echo "masternode=1" >> ioncoin-mn1.conf
$ echo "masternode=1" >> ioncoin-mn1.conf
$ echo "masternodeprivkey=${mngenkey}" >> ioncoin-mn1.conf
$ echo "externalip=${masternodeaddr}" >> ioncoin-mn1.conf
$ echo "port=65431" >> ioncoin-mn1.conf
$ echo "rpcport=65432" >> ioncoin-mn1.conf
$ echo "masternodeaddr=${masternodeaddr}:12700" >> ioncoin-mn1.conf
$ echo "#mn1 ${masternodeaddr}:12700 ${mngenkey} 0" > masternode.conf
$ echo "mn1 ${masternodeaddr}:12700 ${mngenkey} 1" >> masternode.conf
$ 
$ echo "I created new ion address to show Atomsmasher how even one liner could be reused, masternode collateral address: ${mn1address}, genkey: ${mngenkey}, txid: ${txid}, external ip: ${masternodeaddr}. Now imagine that you could use for i in, and setup unlimited amount of mn's (well, limited by coins)";
I created new ion address to show Atomsmasher how even one liner could be reused, masternode collateral address: gHGG3V7GcVY9rL1uRRk96swMSrjjUArBpR, genkey: 91rAqG7rhG1wsx8L1UQppXFKPYkWwqqFu3x2KoisbX1Nc351Cd4, txid: 647c83dbed690ff63076fb176b1256d038e5c1463fb0c9315b838fe4a54c2dfc, external ip: 88.202.231.139. Now imagine that you could use for i in, and setup unlimited amount of mn's (well, limited by coins)
$ 
```
![grafik](https://user-images.githubusercontent.com/24996551/55201724-98c50780-51c4-11e9-8ac8-67754040791b.png)
![grafik](https://user-images.githubusercontent.com/24996551/55201732-a9757d80-51c4-11e9-80da-962c89f6db21.png)
![grafik](https://user-images.githubusercontent.com/24996551/55201750-c27e2e80-51c4-11e9-8fc6-4e73eecc08aa.png)
![grafik](https://user-images.githubusercontent.com/24996551/55201757-d3c73b00-51c4-11e9-9a63-3162b2d0f879.png)

now that is for sure much faster than any previously discussed method. This script is just for demo, so please, dont use it without proper error handlers like what happens if your txid is empty as well as logging of it, loops, etc ... (if run in a loop, rerun a loop until you get txid, example waiting for transactions). Just wanted to show you that everything explained can be done by this very basic script in less than 2 seconds and same way would work with loops and full automation. With that _use cases and who needs something and other dont, for that is cli/debug console best suited if you really want to prevent mistakes and for that, every user would create different scripts for different tasks which might be unrequired for other. WIth that I think there is at all no change in this regard required but if people start asking for it and maybe if there is a budget proposal for that which passes, then why not, its for people not for devs or owners.

feel free to reopen it if you think that I either addressed wrong topic or if you still want to change calling transactions details to launch blockexplorer instead of current popup.
