### ISSUE TITLE
[bug][feature request] Update xion staking rewards

### ISSUE THREAD

**Issue by CeForce** [ioncoincore/ion-v4#37]
Update staking rewards for xion stakes.

This reward schedule should take into account the implementation of IIP_0003

xion staking and masternode reward schedule
    Year 3 - Block reward - 11.5 (5 xion to Staker / 6.5 ion to Masternode)
    Year 4-9 - Block reward - 5.75 (2 xion to Staker/ 3.75 ion to Masternode)
    Year 10 - Block reward - 1.90 (.9 xion to Staker / 1 ion to Masternode)

This is for xion ONLY. No changes to the standard ion stake/masternode splits.

**Comment by FornaxA** [comment]
I am going to implement the xION staking reward as follows:

`xIONStakingReward = floor(BlockReward/2)`

We will need to introduce new denominations to accommodate for the desired block reward in year 10.

**Comment by MitchellCash** [comment]
LGTM

**Comment by FornaxA** [comment]
While staking xION on testnet, the staking output should at the current block height be 9 ION for the masternode and 8 xION for the xION staking wallet. The 9 ION is paid out correctly, however, the xION staking wallet receives 5 xION instead of 8. 

The cause appears to be in `CoinDenomination AmountToClosestDenomination(CAmount nAmount, CAmount& nRemaining)`. After the first iteration, nRemaining (`toMint`) is set to 3, not to 3*COIN.

![screenshot from 2019-01-22 22-59-11](https://user-images.githubusercontent.com/25762277/51568218-7ac3e980-1e99-11e9-840a-743f6b52a384.png)

I can only assume that this is intentional behaviour, because the function has this line of code:
`CAmount nConvert = nAmount / COIN;`
Even though I think this function isn't elegant, I'll avoid messing about with that code for now, and I'll adapt my own code by multiplying the returned amount with COIN.
