### ISSUE TITLE
[feature request][maintenance] Visual Transaction Issue

### ISSUE THREAD

**Issue by XEOHASH** [ioncoincore/ion-v4#60]
**Describe the bug**
When sending 20K to local address (Same Wallet), transaction does not appear in wallets transaction list. Balance does appear to be correct! 

**To Reproduce**
1. Create new wallet address
2. Send coins using coin control to local address

**Expected behavior**
(N/A) with Fee should appear in transaction list, but does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/22961180/51693606-4c472b00-1fcd-11e9-82fb-61ea8bbe6d33.png)
![image](https://user-images.githubusercontent.com/22961180/51693621-523d0c00-1fcd-11e9-881c-6c96f229a31d.png)
![image](https://user-images.githubusercontent.com/22961180/51693637-5a954700-1fcd-11e9-8c40-0cd7093371f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 & Linux
 - Chrome
 - latest

**Smartphone (please complete the following information):**
 - N/A
 - N/A
 - N/A
 - N/A

**Additional context**

**Comment by cevap** [comment]
all tranactions to yourself appear in that way, it only tells you that you did not spend those coins as you sent them to yourself. I think it should be discussed if we change it, as for me it does provide me better overview in point that I dont care about tx which were sent to myself.

On other side you are right, the amount should be shown and actually we could mark it differently that it is tx to ourself.

**Comment by XEOHASH** [comment]
I think all transactions should be shown especially TX with fee's cause they correlate to the wallet balance!
Maybe make it optional for the user! (Show Local TX)

**Comment by cevap** [comment]
if you send to yourself, only costs which you have are fee tranactions. With that it is currently very transparent and does not create "double data" in transaction history. Adding amount that you send to yourself as spent would require additional transaction which will show you that you received them which in general would:

1. have more transactions in your local db
2. due to point one sync would be slower
3. for a user it would be quite intransparent if he sent coins to somebody else to himself
4. would make intransparent how much it costed you to send coins to yourself and would require you to look up each time you want to check it.

I would not agree that it would be good change. We could make put into that additional comment about the amount of the tx sent to yourself, but like stated before, having in history full value requires you to show and save incoming tx as separate and show it. 

please take a look at the dropdown in your transactions history and checkout current logic.

**Comment by raid12345678** [comment]
#80 this is the only complaint from @XEOHASH  on his testing

**Comment by ioncoincore** [comment]
seems it is @raid12345678 , I will mark this one as resolved.

@XEOHASH feel free to reopen this ticket (or anybody else) if you think we still need a change here
